# -*- coding: utf-8 -*-
"""s_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1seXkVbAC21OfXZaaT9V0teSA-O8H4atR
"""

pip install torch

pip install transformers

from transformers import pipeline

model=pipeline('sentiment-analysis')

paragraph="I had an bore day today!.The weather was gloomy and I had a bad time with my friends.I did not get  a promotion at work!."

result=model(paragraph)[0]

if result['label']=='POSITIVE':
  print("the paragraph is positive",result['score'])
else:
  print("the paragraph is negative",result['score'])